import { StyleSheet } from 'react-native';
import { SKETCH_THEME, sketchShadow } from '../../theme/sketchTheme';

export default StyleSheet.create({
  container: {
    ...SKETCH_THEME.layout.container,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SKETCH_THEME.spacing.lg,
    paddingVertical: SKETCH_THEME.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: SKETCH_THEME.colors.border,
    backgroundColor: SKETCH_THEME.colors.uiBg,
  },
  backButton: {
    padding: SKETCH_THEME.spacing.xs,
  },
  headerTitle: {
    ...SKETCH_THEME.typography.h3,
    fontSize: 20,
  },
  avatarContainer: {
      position: 'relative',
      marginBottom: 12,
      alignSelf: 'center',
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#E1E1E1',
    borderWidth: 3,
    borderColor: SKETCH_THEME.colors.card,
  },
  changePhotoButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: SKETCH_THEME.colors.primary,
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: SKETCH_THEME.colors.card,
  },
  helperText: {
      ...SKETCH_THEME.typography.caption,
      marginBottom: 12,
  },
  formContainer: {
      width: '100%',
      maxWidth: 600,
      alignSelf: 'center',
      backgroundColor: SKETCH_THEME.colors.uiBg,
      borderRadius: SKETCH_THEME.radius.lg,
      padding: 16,
      borderWidth: 1,
      borderColor: SKETCH_THEME.colors.border,
      ...(sketchShadow() as object),
      marginBottom: 20,
  },
  label: {
      ...SKETCH_THEME.typography.caption,
      color: SKETCH_THEME.colors.accent,
      textTransform: 'uppercase',
      marginBottom: 2,
      marginTop: 8,
      letterSpacing: 1,
      fontSize: 10,
  },
  value: {
      ...SKETCH_THEME.typography.body,
      paddingVertical: 4,
      fontWeight: '600',
  },
  input: {
      ...SKETCH_THEME.typography.body,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: SKETCH_THEME.colors.border,
      fontWeight: '600',
  },
  readOnly: {
      color: SKETCH_THEME.colors.textMuted,
  },
  logoutButton: {
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
    padding: 10,
    borderRadius: SKETCH_THEME.radius.md,
    backgroundColor: SKETCH_THEME.colors.primarySoft,
    borderWidth: 1,
    borderColor: 'rgba(211, 47, 47, 0.25)',
    alignItems: 'center',
  },
  logoutText: {
    ...SKETCH_THEME.typography.body,
    color: SKETCH_THEME.colors.primary,
    fontWeight: '700',
  },
});
