import { StyleSheet, Platform } from 'react-native';
import { EDITORIAL } from '../../theme/editorialTheme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: EDITORIAL.paper,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 14,
    backgroundColor: EDITORIAL.paper,
    borderBottomWidth: 1,
    borderBottomColor: EDITORIAL.hairline,
  },
  backButton: {
    padding: 6,
  },
  headerTitle: {
    fontFamily: EDITORIAL.fontBold,
    fontSize: 11,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    color: EDITORIAL.grana,
  },
  avatarContainer: {
    position: 'relative',
    marginTop: 18,
    marginBottom: 14,
    alignSelf: 'center',
  },
  avatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: EDITORIAL.hairline,
  },
  changePhotoButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: EDITORIAL.grana,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: EDITORIAL.paper,
  },
  helperText: {
    fontFamily: EDITORIAL.fontRegular,
    fontSize: 12,
    color: EDITORIAL.inkMuted,
    marginBottom: 24,
    textAlign: 'center',
  },
  formContainer: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: EDITORIAL.card,
    borderRadius: 4,
    padding: 22,
    borderWidth: 1,
    borderColor: EDITORIAL.hairline,
    ...Platform.select({
      web: { boxShadow: '0 2px 12px rgba(15,27,45,0.06)' } as any,
      default: {},
    }),
    marginBottom: 20,
  },
  label: {
    fontFamily: EDITORIAL.fontBold,
    fontSize: 10,
    color: EDITORIAL.grana,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 4,
    marginTop: 12,
  },
  value: {
    fontFamily: EDITORIAL.fontRegular,
    fontSize: 15,
    color: EDITORIAL.ink,
    paddingVertical: 8,
  },
  input: {
    fontFamily: EDITORIAL.fontRegular,
    fontSize: 15,
    color: EDITORIAL.ink,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: EDITORIAL.hairline,
  },
  readOnly: {
    color: EDITORIAL.inkMuted,
  },
  logoutButton: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    paddingVertical: 14,
    borderRadius: 4,
    backgroundColor: EDITORIAL.card,
    borderWidth: 1,
    borderColor: EDITORIAL.grana,
    alignItems: 'center',
  },
  logoutText: {
    fontFamily: EDITORIAL.fontBold,
    fontSize: 14,
    color: EDITORIAL.grana,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
});
