import { StyleSheet, Platform } from 'react-native';
import { SKETCH_THEME, sketchFontFamily, sketchShadow } from '../theme/sketchTheme';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: SKETCH_THEME.colors.bg,
    },
    scrollContent: {
        flexGrow: 1,
        padding: 18,
        justifyContent: 'center',
    },
    panel: {
        alignSelf: 'center',
        width: '100%',
        maxWidth: 420,
        backgroundColor: SKETCH_THEME.colors.uiBg,
        borderRadius: 22,
        padding: 22,
        borderWidth: 1,
        borderColor: SKETCH_THEME.colors.border,
        ...(sketchShadow() as object),
    },
    closeButton: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 48 : 18,
        right: 18,
        zIndex: 10,
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: SKETCH_THEME.colors.uiBg,
        borderWidth: 1,
        borderColor: SKETCH_THEME.colors.border,
        ...(sketchShadow() as object),
    },
    closeText: {
        fontSize: 18,
        fontWeight: '800',
        color: SKETCH_THEME.colors.text,
        fontFamily: sketchFontFamily(),
    },
    header: {
        alignItems: 'center',
        marginBottom: 18,
    },
    emoji: {
        fontSize: 56,
        marginBottom: 10,
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
        color: SKETCH_THEME.colors.text,
        textAlign: 'center',
        fontFamily: sketchFontFamily(),
    },
    subtitle: {
        marginTop: 10,
        fontSize: 15,
        color: SKETCH_THEME.colors.textMuted,
        textAlign: 'center',
        lineHeight: 22,
        fontFamily: sketchFontFamily(),
    },
    actions: {
        marginTop: 16,
        width: '100%',
    },
    button: {
        width: '100%',
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: SKETCH_THEME.colors.border,
        ...(sketchShadow() as object),
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '800',
        fontFamily: sketchFontFamily(),
    },
    secondaryButton: {
        backgroundColor: SKETCH_THEME.colors.card,
    },
    darkButton: {
        backgroundColor: SKETCH_THEME.colors.text,
        borderColor: 'rgba(62, 39, 35, 0.55)',
    },
    primaryButton: {
        backgroundColor: SKETCH_THEME.colors.primary,
        borderColor: 'rgba(211, 47, 47, 0.35)',
    },
    primaryButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '800',
        fontFamily: sketchFontFamily(),
    },
    emailLink: {
        paddingVertical: 8,
        alignItems: 'center',
    },
    emailText: {
        color: SKETCH_THEME.colors.primary,
        fontSize: 16,
        fontWeight: '700',
        fontFamily: sketchFontFamily(),
    },
    disclaimer: {
        marginTop: 18,
        fontSize: 12,
        color: SKETCH_THEME.colors.accent,
        textAlign: 'center',
        lineHeight: 18,
        fontFamily: sketchFontFamily(),
    },
    errorContainer: {
        width: '100%',
        padding: 12,
        marginBottom: 14,
        borderRadius: 14,
        backgroundColor: 'rgba(198, 40, 40, 0.10)',
        borderWidth: 1,
        borderColor: 'rgba(198, 40, 40, 0.20)',
    },
    errorText: {
        color: SKETCH_THEME.colors.danger,
        fontSize: 14,
        lineHeight: 20,
        fontFamily: sketchFontFamily(),
    },
    formTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: SKETCH_THEME.colors.text,
        marginBottom: 14,
        textAlign: 'center',
        fontFamily: sketchFontFamily(),
    },
    input: {
        width: '100%',
        borderWidth: 1,
        borderColor: SKETCH_THEME.colors.border,
        borderRadius: 14,
        paddingVertical: 12,
        paddingHorizontal: 14,
        fontSize: 16,
        marginBottom: 12,
        backgroundColor: SKETCH_THEME.colors.card,
        color: SKETCH_THEME.colors.text,
        fontFamily: sketchFontFamily(),
    },
    inlineLink: {
        marginTop: 12,
        padding: 6,
    },
    inlineLinkText: {
        textAlign: 'center',
        color: SKETCH_THEME.colors.textMuted,
        fontFamily: sketchFontFamily(),
    },
});
