// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRY7hQ6c25BFdey1wXrtXEkoc1KvRRAu4',
    appId: '1:767859145063:web:eab2fc2a2b68ae165517c2',
    messagingSenderId: '767859145063',
    projectId: 'trobar-app',
    authDomain: 'trobar-app.firebaseapp.com',
    storageBucket: 'trobar-app.firebasestorage.app',
    measurementId: 'G-J6R1N9KY38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVGwoZ79EU4UpS-fDvn9nRi5owQj0Rxzo',
    appId: '1:767859145063:android:942aa23e0b99ce325517c2',
    messagingSenderId: '767859145063',
    projectId: 'trobar-app',
    storageBucket: 'trobar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dJ992j1iRpJM7hdd7eEvKpad87Tb4ME',
    appId: '1:767859145063:ios:65c56a2645ea86f05517c2',
    messagingSenderId: '767859145063',
    projectId: 'trobar-app',
    storageBucket: 'trobar-app.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4dJ992j1iRpJM7hdd7eEvKpad87Tb4ME',
    appId: '1:767859145063:ios:65c56a2645ea86f05517c2',
    messagingSenderId: '767859145063',
    projectId: 'trobar-app',
    storageBucket: 'trobar-app.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRY7hQ6c25BFdey1wXrtXEkoc1KvRRAu4',
    appId: '1:767859145063:web:1c9393c916b6679a5517c2',
    messagingSenderId: '767859145063',
    projectId: 'trobar-app',
    authDomain: 'trobar-app.firebaseapp.com',
    storageBucket: 'trobar-app.firebasestorage.app',
    measurementId: 'G-051MXED1W5',
  );

}